version: "3"

services:
  ndldb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db

  backend:
    image: backend
    # container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    depends_on:
      - ndldb
    environment:
      - DB_HOST=ndldb
      - DB_PORT=5433
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
    networks:
      - reverse_proxy
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ndlback.rule=Host(`$DOMAIN_NAME`)" 
      - "traefik.http.services.ndlback.loadbalancer.server.port=8080"
      - "traefik.http.routers.ndlback.entrypoints=websecure"
      - "traefik.http.routers.ndlback.tls.certresolver=euroguessr"
      
volumes:
  postgres-data:

networks:
  db:
  reverse_proxy:
    name: infra_monitoring
    external: true
